config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/about'

  resources :users
  resources :recipes do
    resources :recipe_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
	has_many :recipe_comments, dependent: :destroy

	attachment :smoothie_image, destroy: false

	validates :title, :catchphrase, :ingredient, :method, :smoothie_image, presence: true

	def favorited_by?(user)
	favorites.where(user_id: user.id).exists?
	end
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recipe_comments, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: { maximum: 20, minimum: 1 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    recipes_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!

	def create
	  @recipe = Recipe.find(params[:recipe_id])
	  favorite = current_user.favorites.new(recipe_id: @recipe.id)
	  favorite.save
	  redirect_to request.referer
	end

	def destroy
	  @recipe = Recipe.find(params[:recipe_id])
	  favorite = current_user.favorites.find_by(recipe_id: @recipe.id)
	  favorite.destroy
	  redirect_to request.referer
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
      @recipe = Recipe.find(params[:recipe_id])
      @recipe_comment = current_user.recipe_comments.new(recipe_comment_params)
      @recipe_comment.recipe_id = @recipe.id
      if @recipe_comment.save
        flash[:success] = "コメントを投稿しました."
      end
      redirect_to request.referer
    end

    def destroy
      @recipe = Recipe.find(params[:recipe_id])
      recipe_comment = current_user.recipe_comments.find_by(id: params[:id], recipe_id: @recipe.id)
      recipe_comment.destroy
      redirect_to request.referer
    end

    private

    def recipe_comment_params
      params.require(:recipe_comment).permit(:comment)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @search = Recipe.ransack(params[:q])
    @recipes = @search.result.page(params[:page]).reverse_order
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = @recipe.user
    @recipe_comment = RecipeComment.new
    @recipe_comments = @recipe.recipe_comments
  end

  def new
  	@recipe = Recipe.new
  end

  def create
  	@recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
  	  if @recipe.save
        redirect_to recipe_path(@recipe), notice: "レシピを投稿しました"
      else
        @recipes = Recipe.all
        render 'new'
      end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user.id != current_user.id
    redirect_to recipes_path
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: "レシピを編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :catchphrase, :ingredient, :method, :smoothie_image )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :authenticate_user!

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @recipes = @user.recipes
    @my_recipes = Recipe.page(params[:page]).per(9)
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました"
    else
      flash[:notice]="error"
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_comments_helper.rb
module RecipeCommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="main-visual2">
	<div class="welcome">
		<p class="welcome-text2">SMOOTHIE_ROOMとは</p>
	</div>
</div>

<div class="about-text">
	<div class="col-xs-12">
		<h3>SMOOTHIE_ROOM</h3>
		<p>健康・美の意識が</p>
		<p>高まっている現代</p>
		<p>スムージーを飲んで</p>
		<p>心も体も</p>
		<p>元気になろう</p>
		<p>このサイトでは</p>
		<P>投稿されたレシピを見たり</P>
		<P>お気に入りのレシピを</P>
		<P>投稿したりと</P>
		<P>スムージー生活を楽しむことができます</P>
		<p>
			<%= link_to '会員になろう', new_user_registration_path, class: "btn btn-default" %>
		</p>
	</div>
</div>

app/views/home/top.html.erb
<div class="main-visual">
	<div class="welcome">
		<p class="welcome-text">WELCOME TO<br>SMOOTHIE_ROOM</p>
	</div>
</div>

<div class="top-text">
	<div class="col-xs-12">
		<h3>SMOOTHIE_ROOM</h3>
		<p>このサイトはスムージーの</p>
		<p>レシピ投稿サイトになります</p>
		<p>会員でない方も</p>
		<p>レシピの閲覧はできますが、</p>
		<p>レシピの投稿には</p>
		<p>会員登録が必要になります。</p>
		<p>
			<%= link_to 'もっと知る', home_about_path, class: "btn btn-default" %>
			<%= link_to '会員になろう', new_user_registration_path, class: "btn btn-default" %>
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SMOOTHIERoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">

        <nav class="nav navbar-nav navbar-left">
          <span><%= link_to ' SMOOTHIE_ROOM', root_path %></span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' レシピ一覧', recipes_path, class: 'glyphicon glyphicon-cutlery recipes' %></li>
              <li><%= link_to ' レシピ投稿', new_recipe_path, class: 'glyphicon glyphicon-tag recipes' %></li>
              <li><%= link_to ' マイページ', user_path(current_user.id), class: 'glyphicon glyphicon-home users' %></li>
              <li><%= link_to ' user一覧', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' ホーム', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' SMOOTHIE_ROOMとは', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to ' レシピ', recipes_path, class: 'glyphicon glyphicon-cutlery recipes' %></li>
              <li><%= link_to ' 新規登録', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to ' ログイン', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

  <body>
    <div class="container-fluid">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

  </body>

  <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-4 col-xs-offset-8">
              <p>CopyRight SMOOTHIE_ROOM.inc</p>
            </div>
          </div>
        </div>
      </footer>
</html>

app/views/recipes/_recipeform.html.erb
<%= form_for(recipe) do |f| %>
	<% if recipe.errors.any? %>
	<%= recipe.errors.count %>error
	<% recipe.errors.full_messages.each do |message| %>
	<%= message %>
	<% end %>
	<% end %>

  	<div class="col-xs-5">
	    <div class="field row">
			<%= f.label :画像 %>
			<%= f.attachment_field :smoothie_image %>
		</div>
	</div>

	<div class="col-xs-7">
		<div class="field row">
			<%= f.label :レシピ名 %>
			<%= f.text_field :title, class: "col-xs-12 recipe_title" %>
		</div>

		<div class="field row">
			<%= f.label :レシピ紹介 %>
			<%= f.text_area :catchphrase, class: "col-xs-12 recipe_catchphrase" %>
		</div>

		<div class="field row">
			<%= f.label :材料 %>
			<%= f.text_area :ingredient, class: "col-xs-12 recipe_ingredient" %>
		</div>

		<div class="field row">
			<%= f.label :作り方 %>
			<%= f.text_area :method, class: "col-xs-12 recipe_method" %>
		</div>

		<div class="actions row">
			<%= f.submit '投稿する', class: "btn btn-primary col-xs-12" %>
		</div>
	</div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
	<h3>レシピ編集</h3>

	<div class="row">
		<%= render 'recipes/recipeform', recipe: @recipe %>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="container">
	<div class="text-center">
		<h3>recipe</h3>
	</div>

	<div class="row">
		<div class="text-center">
			<h4>
				<%= search_form_for @search do |f| %>
			    <%= f.search_field :title_cont %>
			    <%= f.submit 'レシピを検索する' %>
			    <% end %>
		    </h4>
    	</div>
    </div>

	<div class="smoothie-index">
		<% @recipes.each do |recipe| %>
			<ul>
				<li>
					<div class="smoothie-box">
						<%= link_to recipe_path(recipe.id) do %>
							<%= attachment_image_tag recipe, :smoothie_image, size: "300x280" %>
						<% end %>
						<p><%= recipe.title %></p>
					</div>
				</li>
			</ul>
		<% end %>
	</div>

	<div class="text-center">
		<%= paginate @recipes %>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="container">
	<h3>recipe投稿</h3>

	<div class="row">
		<%= render 'recipes/recipeform', recipe: @recipe %>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="container">
	<h3>レシピ詳細</h3>
	<div class = "row">
		<div class="col-xs-5">
			<%= attachment_image_tag @recipe, :smoothie_image, size: "400x470" %>
		</div>

		<div class="col-xs-7">
			<table class="table table-hover table-inverse">
					<p><tr>
						<h3><%= @recipe.title %></h3><br>
					</tr></p>

					<p><tr>
						<h3><%= @recipe.catchphrase %></h3>
					</tr></p>

					<tr>
						<th>材料</th>
						<td><%= @recipe.ingredient %></td>
					</tr>

					<tr>
						<th>作り方</th>
						<td><%= @recipe.method %></td>
					</tr>

					<tr>
						<th>作成者</th>
						<td><%= link_to @recipe.user.name, user_path(@recipe.user.id) %></td>
					</tr>
			</table>

			<% if current_user == @recipe.user %>
				<%= link_to "レシピを編集する", edit_recipe_path(@recipe), class: "btn-sm btn-success" %>
				<%= link_to "レシピを消す", recipe_path(@recipe), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@recipe.id}" %>
			<% end %>
		</div>
	</div>

    <div class = "row">
        <div class="col-xs-12">
            <h4>
            	<% if @recipe.favorited_by?(current_user) %>
                	いいね数：<%= link_to recipe_favorites_path(@recipe), method: :delete do %>
                		<span class="glyphicon glyphicon-heart"><%= @recipe.favorites.count%></span>
              		<% end %>
           		 <% else %>
             		いいね数：<%= link_to recipe_favorites_path(@recipe), method: :post do %>
               			<span class="glyphicon glyphicon-heart-empty"><%= @recipe.favorites.count %></span>
              		<% end %>
           		 <% end %>
				コメント数：<%= @recipe.recipe_comments.count %>
			</h4>
		</div>
	</div>

	<div class="col-xs-12">

	<div class="comment-form">
		<p>コメントする</p>
		<%= form_for [@recipe, @recipe_comment] do |f| %>
			<%= f.text_area :comment, size: "90x5" %>
	        <%= f.submit '送信', class: "btn-sm btn-primary" %>
	    <% end %>
	</div>

	<table>
	    <% @recipe_comments.each do |recipe_comment| %>
            <tr>
            	<td class="show-comment">
            		<p>ユーザー名：
            			<%= link_to user_path(recipe_comment.user), class: "user_#{recipe_comment.user.id}" do %>
	                		<%= recipe_comment.user.name %>
	                    <% end %>

	                    <% if current_user == recipe_comment.user %>
	            			<%= link_to 'コメントを削除する', recipe_recipe_comment_path(@recipe, recipe_comment), class: 'btn-sm btn-danger', method: :delete %>
	         			<% end %>
	                </p>
	            	<p>コメント：<%= recipe_comment.comment %></p>
	            </td>
	        </tr>
	    <% end %>
	</table>
</div>

</div>

app/views/users/edit.html.erb
<div class="container">
	<h2>User編集</h2>

	<%= form_for(@user) do |f| %>
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
				<ul>
					<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
			<%= f.label :name %>
			<%= f.text_field :name, class: "name" %>
		</div>

		<div class="field">
			<%= f.label :image %>
			<%= f.attachment_field :profile_image, class: "user_image" %>
		</div>

		<div class="field">
			<%= f.label :introduction %>
			<%= f.text_area :introduction, class: "introduction" %>
		</div>

		<div class="actions">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>User一覧</h2>
			<div class="user-index">
				<% @users.each do |user| %>
					<ul>
						<li>
							<div class="user-box">
								<p><%= attachment_image_tag(user, :profile_image, :fill, 200, 200, fallback: "no-image-mini.jpg") %></p>
								<p>名前:<%= user.name %></p>
								<p><%= link_to "ユーザー詳細", user_path(user)%></p>
							</div>
						</li>
					</ul>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="col-xs-4">
		<h3>マイプロフィール</h3>

		<table class="table">
			<tr>
				<%= attachment_image_tag(@user, :profile_image, :fill, 250, 250, fallback: "no_image.jpg") %>
			</tr>

			<tr>
				<th>名前</th>
				<th><%= @user.name %></th>
			</tr>

			<tr>
				<th>自己紹介文</th>
				<th><%= @user.introduction %></th>
			</tr>
		</table>

		<% if current_user == @user %>
			<%= link_to '編集する', edit_user_path(@user), class: "btn btn-primary" %>
		<% end %>
	</div>

	<div class="col-xs-8">
		<h3>マイ投稿レシピ一覧</h3>

		<div class="my-smoothie-index">
			<% @recipes.each do |recipe| %>
				<ul>
					<li>
						<div class="my-smoothie-box">
							<%= link_to recipe_path(recipe.id) do %>
								<%= attachment_image_tag recipe, :smoothie_image, size: "160x160" %>
							<% end %>
							<p><%= recipe.title %></p>
						</div>
					</li>
				</ul>
			<% end %>
		</div>
	</div>

	<div class="text-center">
		<%= paginate @my_recipes %>
	</div>
</div>